# Generated by Django 2.0.3 on 2019-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('uname', models.TextField(max_length=100)),
                ('pwd', models.TextField()),
                ('mno', models.TextField(max_length=10)),
                ('address', models.TextField()),
                ('bid', models.IntegerField()),
                ('doj', models.TextField(max_length=15)),
                ('salary', models.FloatField()),
                ('email', models.TextField(max_length=100)),
                ('branch', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('address', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('fees', models.FloatField()),
                ('bid', models.IntegerField()),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('email', models.TextField(max_length=30)),
                ('mno', models.TextField(max_length=10)),
                ('cid', models.IntegerField()),
                ('bid', models.IntegerField()),
                ('address', models.TextField()),
                ('doj', models.TextField()),
                ('paid', models.FloatField()),
                ('balance', models.FloatField()),
                ('course', models.TextField()),
            ],
        ),
    ]
